# Code generated by:
# Date: April 24, 2017 02:37PM
# Database: tmdbt
# Peewee version: 2.9.2
import json
import os 
dir_path = os.path.dirname(os.path.realpath(__file__))

ini_file = os.path.join(dir_path, "ini.json")

INI = {}

with open("ini.json", "r") as ini:
	INI = json.loads(ini.read())

from peewee import *

#database = MySQLDatabase(INI["tmdbt_mysql"]["db"], **{'host': INI["tmdbt_mysql"]["url"], 'user': INI["tmdbt_mysql"]["user"], 'password': INI["tmdbt_mysql"]["pass"]}) Used for testing
database = MySQLDatabase(INI["tmdb_mysql"]["db"], **{'host': INI["tmdb_mysql"]["url"], 'user': INI["tmdb_mysql"]["user"], 'password': INI["tmdb_mysql"]["pass"]})
database.sql_mode = ""

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class Movies(BaseModel):
    id = IntegerField()
    backdrop_path = TextField(null=True)
    genres = TextField(null=True)
    homepage = TextField(null=True)
    imdb_id = CharField(db_column='imdb_id', null=True)
    overview = TextField(null=True)
    popularity = FloatField(null=True)
    poster_path = TextField(null=True)
    release_date = DateField(null=True)
    release_year = TextField(null=True)  # year
    runtime = IntegerField(null=True)
    tagline = TextField(null=True)
    title = TextField(null=True)
    trailer_key = CharField(null=True)
    trailer_site = CharField(null=True)
    vote_average = FloatField()
    vote_count = IntegerField()
    clean_title = TextField(null=True)		


    class Meta:
        db_table = 'movies'

class Recommendations(BaseModel):
    recommended = IntegerField(db_column='recommended_id')
    tmdbid = IntegerField()

    class Meta:
        db_table = 'recommendations'
        
        
class StevenLu(BaseModel):
    imdb_id = CharField(db_column='imdb_id', null=False)

    class Meta:
        db_table = 'stevenlu'

class AlternativeTitles(BaseModel):		
    id = PrimaryKeyField()		
    alternative_title = TextField(null=True)		
    clean_alt_title = TextField(null=True)		
    iso_3166_1 = CharField(null=True)		
    tmdbid = IntegerField()		
    class Meta:		
        db_table = 'alt_titles'
        
class ReleaseDates(BaseModel):		
    id = PrimaryKeyField()		
    release_date = DateField()		
    note = TextField(null=True)		
    iso_3166_1 = CharField(null=True)
    certification = CharField(null=True)
    iso_639_1 = CharField(null=True)		
    tmdbid = IntegerField()
    release_type = IntegerField(db_column="type")	
    class Meta:		
        db_table = 'release_dates'