query:
  query($issueId:ID!) {
    node(id: $issueId) {
        __typename
        ... on Issue {
          body
          bodyHTML
          bodyText
        }
    }
  }
variables:
  issueId:
    type: jq
    file: ../workflow/event.json
    query: '.issue.node_id'
